# Generated by Django 5.1.7 on 2025-11-20 13:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_notafiscaltomadorsp'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaFiscalNacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj_cpf_tomador', models.CharField(max_length=18, verbose_name='CNPJ/CPF Tomador')),
                ('nome_tomador', models.CharField(max_length=200, verbose_name='Nome/Razão Social')),
                ('inscricao_municipal_tomador', models.CharField(blank=True, max_length=50, null=True, verbose_name='Inscrição Municipal')),
                ('logradouro_tomador', models.CharField(blank=True, max_length=200, null=True, verbose_name='Logradouro')),
                ('numero_tomador', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número')),
                ('complemento_tomador', models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento')),
                ('bairro_tomador', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro')),
                ('cidade_tomador', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade')),
                ('uf_tomador', models.CharField(blank=True, max_length=2, null=True, verbose_name='UF')),
                ('cep_tomador', models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP')),
                ('email_tomador', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('data_emissao', models.DateField(default=django.utils.timezone.now, verbose_name='Data de Emissão')),
                ('cod_servico', models.CharField(max_length=10, verbose_name='Código do Serviço')),
                ('cod_tributacao_municipio', models.CharField(blank=True, max_length=20, null=True, verbose_name='Código Tributação Município')),
                ('descricao', models.TextField(verbose_name='Descrição do Serviço')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor Total')),
                ('deducoes', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Deduções')),
                ('desconto_incondicionado', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Desconto Incondicionado')),
                ('desconto_condicionado', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Desconto Condicionado')),
                ('aliquota_iss', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Alíquota ISS (%)')),
                ('tipo_tributacao', models.CharField(choices=[('T', 'Tributado no Município'), ('F', 'Tributado Fora do Município'), ('I', 'Isento'), ('N', 'Não Tributado')], max_length=1, verbose_name='Tipo de Tributação')),
                ('iss_retido', models.BooleanField(default=False, verbose_name='ISS Retido')),
                ('municipio_incidencia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Município de Incidência')),
                ('ibs_devido', models.BooleanField(default=True, help_text='Imposto sobre Bens e Serviços (Reforma Tributária)', verbose_name='IBS Devido')),
                ('aliquota_ibs', models.DecimalField(decimal_places=2, default=0, help_text='Alíquota do IBS conforme Reforma Tributária', max_digits=5, verbose_name='Alíquota IBS (%)')),
                ('valor_ibs', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valor IBS')),
                ('ibs_retido', models.BooleanField(default=False, verbose_name='IBS Retido na Fonte')),
                ('cbs_devido', models.BooleanField(default=True, help_text='Contribuição sobre Bens e Serviços (Reforma Tributária)', verbose_name='CBS Devido')),
                ('aliquota_cbs', models.DecimalField(decimal_places=2, default=0, help_text='Alíquota da CBS conforme Reforma Tributária', max_digits=5, verbose_name='Alíquota CBS (%)')),
                ('valor_cbs', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valor CBS')),
                ('cbs_retido', models.BooleanField(default=False, verbose_name='CBS Retido na Fonte')),
                ('pis_retido', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='PIS Retido')),
                ('cofins_retido', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='COFINS Retido')),
                ('irrf_retido', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='IRRF Retido')),
                ('csll_retido', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='CSLL Retido')),
                ('inss_retido', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='INSS Retido')),
                ('numero_rps', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número RPS')),
                ('serie_rps', models.CharField(blank=True, max_length=10, null=True, verbose_name='Série RPS')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('status_nfse', models.CharField(choices=[('pendente', 'Pendente'), ('emitida', 'Emitida'), ('cancelada', 'Cancelada'), ('erro', 'Erro')], default='pendente', max_length=20, verbose_name='Status')),
                ('data_importacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Importação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('numero_nfse', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número NFS-e')),
                ('codigo_verificacao', models.CharField(blank=True, max_length=100, null=True, verbose_name='Código de Verificação')),
                ('data_emissao_nfse', models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora Emissão NFS-e')),
                ('link_nfse', models.URLField(blank=True, null=True, verbose_name='Link NFS-e')),
                ('arquivo_pdf', models.CharField(blank=True, max_length=255, null=True, verbose_name='Arquivo PDF')),
                ('mensagem_erro', models.TextField(blank=True, null=True, verbose_name='Mensagem de Erro')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_nacionais', to='core.empresa', verbose_name='Empresa Emissora')),
            ],
            options={
                'verbose_name': 'Nota Fiscal Nacional',
                'verbose_name_plural': 'Notas Fiscais Nacionais',
                'ordering': ['-data_importacao'],
                'indexes': [models.Index(fields=['empresa', 'status_nfse'], name='nfse_nacion_empresa_0d3158_idx'), models.Index(fields=['data_emissao'], name='nfse_nacion_data_em_0d9ebc_idx'), models.Index(fields=['numero_nfse'], name='nfse_nacion_numero__3b67c0_idx')],
            },
        ),
    ]
