# Generated by Django 4.2.7 on 2025-11-20 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfse_nacional', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notafiscalnacional',
            name='cnpj_contribuinte',
            field=models.CharField(default=1, help_text='CNPJ da empresa emissora', max_length=18, verbose_name='CNPJ Contribuinte'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='notafiscalnacional',
            index=models.Index(fields=['cnpj_contribuinte'], name='nfse_nacion_cnpj_co_342875_idx'),
        ),
    ]
