# Generated by Django 5.1.7 on 2025-11-26 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_empresa_empresa_contratante_and_more'),
        ('nfse_nacional', '0002_notafiscalnacional_cnpj_contribuinte_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notafiscalnacional',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_nacionais', to='core.empresa', verbose_name='Empresa Emissora'),
        ),
    ]
