# Generated by Django 5.1.7 on 2025-11-27 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfse_nacional', '0003_alter_notafiscalnacional_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notafiscalnacional',
            name='cnpj_cpf_tomador',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='CNPJ/CPF Tomador'),
        ),
    ]
