# Generated by Django 5.1.7 on 2025-11-20 00:42

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0006_remove_empresacontratante_certificado_arquivo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(help_text='CNPJ da empresa emissora', max_length=18, unique=True, validators=[core.models.validate_cnpj], verbose_name='CNPJ')),
                ('razao_social', models.CharField(max_length=255, verbose_name='Razão Social')),
                ('nome_fantasia', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Fantasia')),
                ('inscricao_municipal', models.CharField(blank=True, max_length=50, null=True, verbose_name='Inscrição Municipal')),
                ('inscricao_estadual', models.CharField(blank=True, max_length=50, null=True, verbose_name='Inscrição Estadual')),
                ('logradouro', models.CharField(blank=True, max_length=255, null=True, verbose_name='Logradouro')),
                ('numero', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento')),
                ('bairro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro')),
                ('cidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade')),
                ('uf', models.CharField(blank=True, max_length=2, null=True, verbose_name='UF')),
                ('cep', models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('senha_certificado', models.CharField(blank=True, help_text='Senha do certificado digital A1', max_length=255, null=True, verbose_name='Senha do Certificado')),
                ('certificado_arquivo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do Arquivo do Certificado')),
                ('certificado_validade', models.DateField(blank=True, null=True, verbose_name='Validade do Certificado')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('empresa_contratante', models.ForeignKey(help_text='Empresa que contratou o sistema', on_delete=django.db.models.deletion.CASCADE, related_name='empresas_emissoras', to='accounts.empresacontratante', verbose_name='Empresa Contratante')),
            ],
            options={
                'verbose_name': 'Empresa Emissora',
                'verbose_name_plural': 'Empresas Emissoras',
                'ordering': ['-data_cadastro'],
            },
        ),
    ]
