# Generated by Django 5.1.7 on 2025-11-20 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaFiscalSP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj_cpf_tomador', models.CharField(max_length=18, verbose_name='CNPJ/CPF Tomador')),
                ('nome_tomador', models.CharField(max_length=255, verbose_name='Nome/Razão Social Tomador')),
                ('cep_tomador', models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP')),
                ('logradouro_tomador', models.CharField(blank=True, max_length=255, null=True, verbose_name='Logradouro')),
                ('numero_tomador', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número')),
                ('bairro_tomador', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro')),
                ('cidade_tomador', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade')),
                ('uf_tomador', models.CharField(blank=True, max_length=2, null=True, verbose_name='UF')),
                ('email_tomador', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('cod_servico', models.CharField(max_length=10, verbose_name='Código do Serviço')),
                ('descricao', models.TextField(verbose_name='Descrição do Serviço')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor Total')),
                ('deducoes', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Deduções')),
                ('aliquota', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Alíquota (%)')),
                ('tipo_tributacao', models.CharField(choices=[('T', 'Tributado no Município'), ('F', 'Tributado Fora do Município'), ('I', 'Isento'), ('N', 'Não Tributado')], max_length=1, verbose_name='Tipo de Tributação')),
                ('iss_retido', models.BooleanField(default=False, verbose_name='ISS Retido')),
                ('pis_retido', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='PIS Retido')),
                ('cofins_retido', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='COFINS Retido')),
                ('irrf_retido', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='IRRF Retido')),
                ('csll_retido', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='CSLL Retido')),
                ('inss_retido', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='INSS Retido')),
                ('status_rps', models.CharField(choices=[('pendente', 'Pendente'), ('emitida', 'Emitida'), ('cancelada', 'Cancelada'), ('erro', 'Erro')], default='pendente', max_length=20, verbose_name='Status')),
                ('data_emissao', models.DateField(blank=True, null=True, verbose_name='Data de Emissão')),
                ('data_importacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Importação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('numero_nfse', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número NFS-e')),
                ('codigo_verificacao', models.CharField(blank=True, max_length=100, null=True, verbose_name='Código de Verificação')),
                ('data_emissao_nfse', models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora Emissão NFS-e')),
                ('link_nfse', models.URLField(blank=True, null=True, verbose_name='Link NFS-e')),
                ('arquivo_pdf', models.CharField(blank=True, max_length=255, null=True, verbose_name='Arquivo PDF')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('mensagem_erro', models.TextField(blank=True, null=True, verbose_name='Mensagem de Erro')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_fiscais', to='core.empresa', verbose_name='Empresa Prestadora')),
            ],
            options={
                'verbose_name': 'Nota Fiscal SP',
                'verbose_name_plural': 'Notas Fiscais SP',
                'ordering': ['-data_importacao'],
                'indexes': [models.Index(fields=['empresa', 'status_rps'], name='core_notafi_empresa_79a0ce_idx'), models.Index(fields=['data_emissao'], name='core_notafi_data_em_6b6894_idx'), models.Index(fields=['numero_nfse'], name='core_notafi_numero__fe7d8a_idx')],
            },
        ),
    ]
