# Generated by Django 5.1.7 on 2025-11-20 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_notafiscalsp'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='cpf_cnpj_procurador',
            field=models.CharField(blank=True, help_text='CPF ou CNPJ do procurador', max_length=18, null=True, verbose_name='CPF/CNPJ do Procurador'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='tem_procurador',
            field=models.BooleanField(default=False, help_text='Marque se a empresa possui procurador', verbose_name='Possui Procurador'),
        ),
    ]
