# Generated by Django 5.1.7 on 2025-11-20 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_empresa_cpf_cnpj_procurador_empresa_tem_procurador'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaFiscalTomadorSP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj_tomador', models.CharField(max_length=18, verbose_name='CNPJ Tomador')),
                ('inscricao_municipal', models.CharField(max_length=50, verbose_name='Inscrição Municipal')),
                ('data_prestacao_servico', models.DateField(verbose_name='Data de Prestação do Serviço')),
                ('cnpj_cpf_prestador', models.CharField(max_length=18, verbose_name='CNPJ/CPF Prestador')),
                ('numero_documento', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número do Documento')),
                ('serie', models.CharField(blank=True, max_length=10, null=True, verbose_name='Série')),
                ('cidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade')),
                ('estado', models.CharField(blank=True, max_length=2, null=True, verbose_name='Estado')),
                ('cep', models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP')),
                ('cod_servico', models.CharField(max_length=10, verbose_name='Código do Serviço')),
                ('descricao', models.TextField(verbose_name='Descrição do Serviço')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor Total')),
                ('deducoes', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Deduções')),
                ('aliquota', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Alíquota (%)')),
                ('tipo_tributacao', models.CharField(choices=[('T', 'Tributado no Município'), ('F', 'Tributado Fora do Município'), ('I', 'Isento'), ('N', 'Não Tributado')], max_length=1, verbose_name='Tipo de Tributação')),
                ('regime_tributacao', models.CharField(choices=[('simples', 'Simples Nacional'), ('presumido', 'Lucro Presumido'), ('real', 'Lucro Real'), ('mei', 'MEI')], max_length=20, verbose_name='Regime de Tributação')),
                ('tipo_documento', models.CharField(choices=[('nfe', 'NF-e'), ('nfse', 'NFS-e'), ('cupom', 'Cupom Fiscal'), ('recibo', 'Recibo')], max_length=20, verbose_name='Tipo de Documento')),
                ('iss_retido', models.BooleanField(default=False, verbose_name='ISS Retido')),
                ('nfts', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número NFTS')),
                ('status_nfts', models.CharField(choices=[('pendente', 'Pendente'), ('emitida', 'Emitida'), ('cancelada', 'Cancelada'), ('erro', 'Erro')], default='pendente', max_length=20, verbose_name='Status')),
                ('data_importacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Importação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('protocolo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Protocolo')),
                ('data_emissao_nfts', models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora Emissão NFTS')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('mensagem_erro', models.TextField(blank=True, null=True, verbose_name='Mensagem de Erro')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_tomador', to='core.empresa', verbose_name='Empresa Tomadora')),
            ],
            options={
                'verbose_name': 'Nota Fiscal Tomador SP',
                'verbose_name_plural': 'Notas Fiscais Tomador SP',
                'ordering': ['-data_importacao'],
                'indexes': [models.Index(fields=['empresa', 'status_nfts'], name='core_notafi_empresa_6cc47f_idx'), models.Index(fields=['data_prestacao_servico'], name='core_notafi_data_pr_43b81c_idx'), models.Index(fields=['nfts'], name='core_notafi_nfts_41f6df_idx')],
            },
        ),
    ]
