# Generated by Django 4.2.7 on 2025-11-20 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_notafiscaltomadorsp'),
    ]

    operations = [
        migrations.AddField(
            model_name='notafiscalsp',
            name='numero_rps',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Número RPS'),
        ),
        migrations.AddField(
            model_name='notafiscalsp',
            name='serie_rps',
            field=models.CharField(blank=True, default='RPS', max_length=5, verbose_name='Série RPS'),
        ),
        migrations.AddField(
            model_name='notafiscalsp',
            name='tributacao_rps',
            field=models.CharField(blank=True, choices=[('T', 'Tributado no Município'), ('F', 'Tributado Fora do Município'), ('I', 'Isento'), ('N', 'Não Tributado')], max_length=1, null=True, verbose_name='Tributação RPS'),
        ),
    ]
