# Generated by Django 4.2.7 on 2025-11-20 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_notafiscalsp_numero_rps_notafiscalsp_serie_rps_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notafiscalsp',
            name='cnpj_contribuinte',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='CNPJ Contribuinte'),
        ),
        migrations.AddField(
            model_name='notafiscaltomadorsp',
            name='cnpj_contribuinte',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='CNPJ Contribuinte'),
        ),
    ]
