# Generated by Django 5.1.7 on 2025-11-26 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_userprofile_empresa'),
        ('core', '0006_notafiscalsp_cnpj_contribuinte_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='empresa_contratante',
            field=models.ForeignKey(blank=True, help_text='Empresa que contratou o sistema', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empresas_emissoras', to='accounts.empresacontratante', verbose_name='Empresa Contratante'),
        ),
        migrations.AlterField(
            model_name='notafiscalsp',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_fiscais', to='core.empresa', verbose_name='Empresa Prestadora'),
        ),
        migrations.AlterField(
            model_name='notafiscaltomadorsp',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_tomador', to='core.empresa', verbose_name='Empresa Tomadora'),
        ),
    ]
