# Generated by Django 5.1.7 on 2025-11-27 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_empresa_empresa_contratante_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notafiscalsp',
            name='cnpj_cpf_tomador',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='CNPJ/CPF Tomador'),
        ),
    ]
