# Generated by Django 5.1.7 on 2025-06-22 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('cnpj_empresa', models.CharField(max_length=18, verbose_name='CNPJ da Empresa')),
                ('nome_empresa', models.CharField(max_length=255, verbose_name='Nome da Empresa')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('status', models.CharField(choices=[('teste', 'Em Teste'), ('ativo', 'Ativo'), ('expirado', 'Expirado'), ('bloqueado', 'Bloqueado'), ('vencido', 'Vencido'), ('suspenso', 'Suspenso')], default='teste', max_length=10, verbose_name='Status')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_expiracao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Expiração')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuário',
                'verbose_name_plural': 'Perfis de Usuários',
            },
        ),
    ]
