# Generated by Django 5.1.7 on 2025-07-26 23:14

import accounts.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaContratante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj_cpf', models.CharField(max_length=18, unique=True, validators=[accounts.models.validate_cnpj_cpf], verbose_name='CNPJ ou CPF')),
                ('nome_razao', models.CharField(max_length=255, verbose_name='Razão Social / Nome')),
                ('nome_fantasia', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Fantasia')),
                ('num_usuarios', models.PositiveIntegerField(default=1, verbose_name='Limite de Usuários')),
                ('status', models.CharField(choices=[('teste', 'Em Teste'), ('ativo', 'Ativo'), ('expirado', 'Expirado'), ('bloqueado', 'Bloqueado'), ('vencido', 'Vencido'), ('suspenso', 'Suspenso')], default='teste', max_length=10, verbose_name='Status')),
                ('plano', models.CharField(choices=[('padrao', 'Padrão'), ('pro', 'Pro')], default='padrao', max_length=20, verbose_name='Plano')),
                ('vencimento', models.DateField(blank=True, null=True, verbose_name='Vencimento')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
            ],
            options={
                'verbose_name': 'Empresa Contratante',
                'verbose_name_plural': 'Empresas Contratantes',
            },
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='cnpj_empresa',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='data_expiracao',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='nome_empresa',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='status',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='accounts.empresacontratante'),
        ),
    ]
