# Generated by Django 5.1.7 on 2025-07-26 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_empresacontratante_remove_userprofile_cnpj_empresa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresacontratante',
            name='num_empresas',
            field=models.PositiveIntegerField(default=1, verbose_name='Limite de Empresas'),
        ),
    ]
