# Generated by Django 5.1.7 on 2025-07-26 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_empresacontratante_num_empresas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresacontratante',
            name='nome_fantasia',
        ),
        migrations.AddField(
            model_name='empresacontratante',
            name='usuarios_cadastrados',
            field=models.PositiveIntegerField(default=1, verbose_name='Usuários Cadastrados'),
        ),
    ]
