# Generated by Django 4.2.7 on 2025-11-20 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_empresacontratante_nome_fantasia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresacontratante',
            name='certificado_arquivo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do Arquivo do Certificado'),
        ),
        migrations.AddField(
            model_name='empresacontratante',
            name='certificado_validade',
            field=models.DateField(blank=True, null=True, verbose_name='Validade do Certificado'),
        ),
        migrations.AddField(
            model_name='empresacontratante',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Última Atualização'),
        ),
        migrations.AddField(
            model_name='empresacontratante',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de Cadastro'),
        ),
        migrations.AddField(
            model_name='empresacontratante',
            name='inscricao_municipal',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Inscrição Municipal'),
        ),
        migrations.AddField(
            model_name='empresacontratante',
            name='senha_certificado',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Senha do Certificado'),
        ),
    ]
