# Generated by Django 4.2.7 on 2025-11-20 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_empresacontratante_certificado_arquivo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresacontratante',
            name='certificado_arquivo',
        ),
        migrations.RemoveField(
            model_name='empresacontratante',
            name='certificado_validade',
        ),
        migrations.RemoveField(
            model_name='empresacontratante',
            name='data_atualizacao',
        ),
        migrations.RemoveField(
            model_name='empresacontratante',
            name='data_cadastro',
        ),
        migrations.RemoveField(
            model_name='empresacontratante',
            name='inscricao_municipal',
        ),
        migrations.RemoveField(
            model_name='empresacontratante',
            name='senha_certificado',
        ),
    ]
